# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]


[[constraint]]
  branch = "master"
  name = "github.com/gopherjs/gopherjs"

[[constraint]]
  branch = "master"
  name = "github.com/gopherjs/websocket"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[prune]
  go-tests = true
  unused-packages = true
  #   non-go = false
