# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.13.1
    working_directory: /go/src/github.com/lologarithm/netgen
    steps:
      - checkout
      - run: GO111MODULE=on go install ./cmd/netgen/
      - run: netgen --dir=./benchmark/models
      - run: netgen --dir=./example/newmodels
      - run: netgen --dir=./example/models
      - run: GO111MODULE=on go test -v ./...
