# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.12.6
    working_directory: /go/src/github.com/lologarithm/netgen
    steps:
      - checkout
      - run: go install ./cmd/netgen/
      - run: netgen --dir=./benchmark
      - run: netgen --dir=./example/newmodels
      - run: netgen --dir=./example/models
      - run: go test -v ./...
      # - run: gopherjs test -v ./ngen/...
