// GENERATED BY netgen tool on Oct 4 2018 00:47 MDT
package models

import (
	"github.com/lologarithm/netgen/lib/ngen"
)


const (
	UnknownMsgType ngen.MessageType = iota
	AckMsgType
	MessageMsgType
)

// ParseNetMessage accepts input of raw bytes from a NetMessage. Parses and returns a Net message.
func ParseNetMessage(packet ngen.Packet, content *ngen.Buffer) ngen.Net {
	switch packet.Header.MsgType {
	case MessageMsgType:
		msg := MessageDeserialize(content)
		return &msg
	default:
		return nil
	}
}


func MessageDeserialize(buffer *ngen.Buffer) (m Message) {
	m.Message, _ = buffer.ReadString()
	return m
}
